### ISSUE TITLE
Bug on data_gen.py

### ISSUE THREAD

**Issue by JoonyoungYi** [AlexGidiotis/keras-CF-NADE#1]
First of all, thank you for putting this nice repository.
I really appreciate your effort to make this code.
I found a minor bug while I investigate your code for my own purpose.
There is a bug in the python file `data_gen.py` in 153-th line.
You would better change "if" to "elif". Thanks!

**Comment by AlexGidiotis** [comment]
@JoonyoungYi that is correct. It has been fixed. Thanks for the feedback.
